Add MKE and CVE-2024-21626: Understanding the Potential Impact and Mitigation
Mirantis/security pull request #4
Opened 2024-02-06 16:52 UTC by ry4nz

Add 0011 Advisories

2024-02-06 21:42 UTC, corhere requested changes

2024-02-06 21:42 UTC, corhere commented on advisories/0011.md
> +This advisory addresses the impact of CVE-2024-21626, a critical vulnerability identified within runc, and its implications for the Mirantis Kubernetes Engine (MKE). Given that MKE relies heavily on
```suggestion
This advisory addresses the impact of CVE-2024-21626, a vulnerability identified within runc, and its implications for the Mirantis Kubernetes Engine (MKE). Given that MKE relies heavily on the Mirantis Container Runtime (MCR), this vulnerability directly impacts its operational integrity. We aim to clarify the situation, explain the mitigation steps, and provide actionable guidance for MKE users.
```
It's not a critical vulnerability; see line 11 of this very document.

2024-02-06 21:42 UTC, corhere commented on advisories/0011.md
> +3. The MKE cluster is vunerable if and only if the version <= 23.0.9.
Check the runc version, not Engine.

2024-02-06 21:42 UTC, corhere commented on advisories/0011.md
> +* MKE deployment requires installation of MCR.  Older versions of MCR (<= 23.0.9) contain a vulnerability in the underlying runc component. Please see [the MCR advisory](https://github.com/Mirantis/s
```suggestion
* MKE deployment requires installation of MCR.  Older versions of the MCR packages contain a vulnerable version of the runc component. Please see [the MCR advisory](https://github.com/Mirantis/security/blob/main/advisories/0010.md) for details.
```

The vulnerable versions and patching steps have some nuance that is neither correctly nor adequately captured here.

2024-02-06 21:42 UTC, corhere commented on advisories/0011.md
> +* Consider backing up your cluster configuration before making any significant changes.
```suggestion
```

Leave the instructions to the Engine team, please.

2024-02-06 21:42 UTC, corhere commented on advisories/0011.md
> +#### How to check if MKE is vulnerable
But you just said MKE was not vulnerable...

2024-02-06 21:42 UTC, corhere commented on advisories/0011.md
> +   While CVE-2024-21626 might appear in vulnerability scans of your MKE images due to a dependent library, an update to MKE images is not currently required. MKE's architecture mitigates the vulnerab
> MKE's architecture mitigates the vulnerability, and there's no known exploit path within MKE.

That statement could be easily misinterpreted as "MKE protects you from the runc vulnerability." MKE _components_ are not vulnerable to this particular exploit, but MKE _does not protect users from harm_ if they ran a malicious container image with a vulnerable runc installed.

2024-02-06 22:22 UTC, ry4nz commented on advisories/0011.md
> +3. The MKE cluster is vunerable if and only if the version <= 23.0.9.
While I understand the root cause lies with runc, MKE customers interact directly with MCR, not runc. Therefore, focusing on MCR version checks seems more relevant.

2024-02-06 22:41 UTC, corhere commented on advisories/0011.md
> +3. The MKE cluster is vunerable if and only if the version <= 23.0.9.
Users will remain vulnerable if they upgrade their docker-ee package without upgrading their containerd.io package, as is possible (at least) on RPM distros. The _only_ way to tell for sure is to check the version of runc, **which docker version already conveniently outputs**

2024-02-07 05:39 UTC, ry4nz commented on advisories/0011.md
> +* MKE deployment requires installation of MCR.  Older versions of MCR (<= 23.0.9) contain a vulnerability in the underlying runc component. Please see [the MCR advisory](https://github.com/Mirantis/s
While you could technically install individual packages like Docker-EE, Docker-EE-CLI, and containerd, Mirantis does not officially support such a configuration. Customers and Mirantis typically and should always treat MCR as a single, integrated product that includes all these components pre-configured and tested for compatibility. Using MCR ensures a supported and well-maintained environment, avoiding potential issues arising from manual package installation and management.

2024-02-07 05:53 UTC, ry4nz commented on advisories/0011.md
> +   While CVE-2024-21626 might appear in vulnerability scans of your MKE images due to a dependent library, an update to MKE images is not currently required. MKE's architecture mitigates the vulnerab
Let me rewrite this paragraph

2024-02-07 05:54 UTC, ry4nz commented on advisories/0011.md
> +3. The MKE cluster is vunerable if and only if the version <= 23.0.9.
I may add a check to `runc` and perhaps an after-upgrade check as well.  However please check https://github.com/Mirantis/security/pull/4/files#r1480921670 for my understanding of MCR as a product.

2024-02-07 05:59 UTC, ry4nz commented on advisories/0011.md
> +#### How to check if MKE is vulnerable
MKE as a product, is vulnerable due to it's dependency to MCR.  On the other hand, MKE images are not vulnerable and thus an update is not necessary.

2024-02-07 16:05 UTC, byDimasik commented on advisories/0011.md
> +3. The MKE cluster is vunerable if and only if the version <= 23.0.9.
```suggestion
3. The MKE cluster is vulnerable if and only if the version <= 23.0.9.
```

2024-02-07 17:46 UTC, corhere commented on advisories/0011.md
> +3. The MKE cluster is vunerable if and only if the version <= 23.0.9.
We want users to always treat MCR as a single integrated product but we distribute it as four separate DEB/RPM packages. There are all sorts of ways that users may get their deployments into an unsupported state, intentionally or by accident. Users do weird things, make mistakes, or they might even do everything right but fall victim to a software bug during upgrade. Users are going to use these instructions to to verify that they have applied the update correctly. Instructions which incorrectly tell users they are not vulnerable if they applied the update incorrectly are worse than useless, _they put our customers at risk_.

2024-02-07 21:03 UTC, corhere commented on advisories/0011.md
> +   docker version --format "{{range .Server.Components}}{{if eq .Name \"runc\"}}{{.Version}}{{end}}{{end}}"
```suggestion
   docker version --format '{{range .Server.Components}}{{if eq .Name "runc"}}{{.Version}}{{end}}{{end}}'
```

2024-02-07 21:07 UTC, corhere commented on advisories/0011.md
> +#### How to check if MKE is vulnerable
```suggestion
#### How to check if your MKE cluster is vulnerable
```

2024-02-07 21:07 UTC, corhere commented on advisories/0011.md
> +   docker version --format "{{range .Server.Components}}{{if eq .Name \"runc\"}}{{.Version}}{{end}}{{end}}"
Wouldn't that only check the runc version installed on one of the manager nodes? Or does MKE do some magic in the Engine API proxy? How would a user check the rest of the nodes in their cluster?

2024-02-07 23:49 UTC, ry4nz commented on advisories/0011.md
> +   docker version --format "{{range .Server.Components}}{{if eq .Name \"runc\"}}{{.Version}}{{end}}{{end}}"
`docker node ls --format {{.EngineVersion}}` to check engine version.  There is no viable way other than `ssh` into nodes.

2024-02-08 16:25 UTC, corhere approved these changes

2024-02-08 18:15 UTC, ameyag approved these changes

2024-02-08 23:41 UTC, merged